version: '3.7'
services:
    backend:
        build:
            context: .
            dockerfile: containers/backend/Dockerfile
        container_name: house-backend
        ports:
            - 127.0.0.1:${API_PORT}:80
        env_file:
            - ./envs/dev.env
        environment:
            MODULE_NAME: main
            LOG_LEVEL: ${LOG_LEVEL}
            WORKERS_PER_CORE: 1
            WEB_CONCURRENCY: 1
    frontend:
        build:
            context: ./frontend
            dockerfile: containers/frontend/Dockerfile
        container_name: house-frontend
        ports:
            - 127.0.0.1:${FRONTEND_PORT}:80
        environment:
            REACT_APP_API_URL: localhost:${API_PORT}
            REACT_APP_API_SECRET: ${API_SECRET}
