version: '3.7'
services:
    backend:
        build:
            context: .
            dockerfile: containers/backend/Dockerfile
        container_name: house-backend
        ports:
            - 127.0.0.1:${API_PORT}:80
        env_file:
            - ./envs/dev.env
        environment:
            MODULE_NAME: main
            LOG_LEVEL: ${LOG_LEVEL}
            WORKERS_PER_CORE: 1
            WEB_CONCURRENCY: 1
    frontend:
        build:
            context: .
            dockerfile: containers/frontend/Dockerfile
            args:
                ENV_FILE: ./envs/frontend.${BUILD_TARGET}.env
        container_name: house-frontend
        ports:
            - 127.0.0.1:${FRONTEND_PORT}:80
